version: '3.9'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: readingisgood
  readingisgood:
    image: readingisgood
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8991:8991
    depends_on:
      - mongodb
    environment:
      HOST: mongodb
      PORT: 27017
      USERNAME: readingisgoodUser
      PASSWORD: password
